### ISSUE TITLE
Why are two games created instead of one? (and 4 instead of 2 if simulating 2 users)

### ISSUE THREAD

**Issue by jopvanheesch** [languageininteraction/TacitCommunicationGame#109]

**Comment by Woseseltops** [comment]
Two more weird characteristics:
* Everything (not just game) you put in the declaration has this problem of being created multiple times
* The declaration seems to be run an arbitrary amount of times: I one time got 16 Game inits (8 for each screen)!

Hypotheses:
* Multiple HomeViewControllers are created, but only one is used
* The HomeViewController declaration process is run multiple times, which apparently is not a problem to the code

**Comment by jopvanheesch** [comment]
Let's give this up for now
